

name: JPG Mover

on:
  push:
    paths:
      '**.jpg'
  pull_request:
    paths:
      '**.jpg'

  workflow_dispatch:

jobs:

  move-jpgs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Move jpg files
        run: mv *.jpg Images

      - name: Commit the changes
        run: |
          git config user.name 'DanielBrett'
          git config user.email 'dbrett@brocku.ca'
          git add .
          git commit -m "JPG Mover was activated"
          git push
